eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

management:
    context-path: /admin
    port: 9001
server:
    port: 8761
spring:
    application:
        name: eureka-server
