eureka:
    client:
      service-url:
        defaultZone: http://eureka-server:8761/eureka/
    instance:
        prefer-ip-address: true
management:
    context-path: /admin
server:
    port: 0
spring:
    application:
        name: eureka-client2





