server:
    port: 0
spring:
    application:
        name: WalletService
eureka:
    client:
      service-url:
        defaultZone: http://${EUREKA_SERVER}:8761/eureka/
    instance:
        prefer-ip-address: true
        status-page-url-path: ${management.context-path}/info